### PR TITLE
Fixed #590 Delete folder-issue in Post Processor and added more granu…

### LINKED ISSUE #590: PostProcessorBootstrapper - Delete folder throws error
During the startup of the Post Processor the resources are copied to the temp-catalog. During this there is a "Delete"-call if the folder already exsists.

This fails if there is content in the folder (which it it).

PR is comming

### PR DESCRIPTION
**Pull request by enkelmedia**
Not the biggest PR ever - but a very important one ;)

// m

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Ah fantastic. Thank you!

**Comment by JimBobSquarePants** [comment]
Just released this was made against master. Develop is my default branch 😞 Trying to figure out how to re-merge it without getting you to submit another PR.

**Comment by JimBobSquarePants** [comment]
Just did it manually and now pushed a 1.2.2. release. Thanks again!

**Comment by enkelmedia** [comment]
Ohh :/ My bad! Should have worked on dev of course :)

**Comment by JimBobSquarePants** [comment]
No worries 😄

**Pull request merged**
