### PR TITLE
Adding basic middleware and web test projects.

### PR DESCRIPTION
**Pull request by PromontoryProtean**
This pull request supersedes #318. I will close #318 if this works as intended.

### CODE REVIEW

**Comment by PromontoryProtean** [comment]
Hey Jim, I was tied up with a client migration but finally had some time to revisit this. Not sure if I went about it correctly. Couldn't figure out a way to change the target branch on my original pull request, so I created a new pull request after creating a new Core-Web branch in my fork. Not sure if the old conversation will be lost. Hopefully this will work.

**Comment by PromontoryProtean** [comment]
Just checking back on this and if you changed your mind. Curious what the idea you mentioned for the web branch is.

**Comment by JimBobSquarePants** [comment]
Nah, not changed my mind. Just had a couple of big bugs in the jpeg decoder to get fixed first. 

My approach will actually be laughably simple. 

Something like.

``` csharp
public class Resize : IWebImageProcessor {

    public int Index GetIndex (NameValueCollection querystring){
        // Calculate the position in the querystring params.
        // Parse querystring to get width , height or other properties which are private. 
    }    
   
    public Image Process (Image image){
    
        // width, height are private 
         return image.Resize(this.width, this.height);
    }
}
```

I'll have an extension method to `Image `that loops through all known `IWebImageProcessor` types and assigns the correct one.

Something like that anyway...

**Comment by JimBobSquarePants** [comment]
Think I best merge this before everything changes for RC2! Thanks so much for your patience and contribution.

**Pull request merged**
