### PR TITLE
Query string corruption in ImageProcessingModule when using presets

### PR DESCRIPTION
**Pull request by ronaldbarendse**
This fixes issue #727.

### CODE REVIEW

**Comment by ronaldbarendse** [comment]
Also: what was the reason for using the `Regex.Replace` instead of a simple `String.Replace` in the previous code? `match.Value` could even contain valid regex patterns and cause unexpected replacements, so should be properly escaped first using [`Regex.Escape`](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.escape).

This should probably still be done on this line: https://github.com/JimBobSquarePants/ImageProcessor/blob/21c4e284a80a8f3c63f89e0bdad2814740b4a0ba/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L491

This could also be rewritten to use a combination of `String.IndexOf()` and `String.Substring()` calls, as the `String.Replace` method doesn't support case insensitivity...

**Comment by JimBobSquarePants** [comment]
To answer your question. I wrote it about 4 years ago

**Comment by ronaldbarendse** [comment]
I've looked into the query string processing code and it seems the casing of the URL/query string is kept intact, so ideally all matching/replacing should support different casings (especially because `Request.QueryString` is a `NameValueCollection` that already is case-insensitive and is used in combination with the regex matching)...

So all `Regex` instances in the `IWebGraphicsProcessor` classes should at least get a `RegexOptions.IgnoreCase` (and also `RegexOptions.CultureInvariant` and `RegexOptions.ExplicitCapture` while we're at it). Any regex pattern should also be escaped, like the `servicePrefix` in the `UrlParser.ParseUrl` method (as the dot in 'appdata.axd', 'database.axd' and 'remote.axd' currently means _any_ character):
https://github.com/JimBobSquarePants/ImageProcessor/blob/bab08e8f370989616d2283de1921cd41e3f04d41/src/ImageProcessor.Web/Helpers/UrlParser.cs#L38

I know this library is in maintenance mode, but it still widely used (e.g. all Umbraco sites). I don't mind putting some effort into this (basically adding some `RegexOptions` and checking for case sensitivity), if you're willing to accept more PRs for this 😉 I already spotted some performance improvements by moving Regex instances to static fields, etc.

**Comment by JimBobSquarePants** [comment]
@ronaldbarendse As long as I don't need to do much work and the PRs give obvious benefit I'm happy to accept more.

**Comment by ronaldbarendse** [comment]
I've added escaping to the `Regex.Replace()` (query string) and `Regex.Split()` (service prefix) patterns, so invalid input doesn't throw the following exception:
```
System.ArgumentException: parsing "center=0.52830188679245282,0.688&mode=crop&width=2560&height=1440&rnd=131842653730000000\" - Illegal \ at end of pattern.
 at System.Text.RegularExpressions.RegexParser.ScanBackslash()
 at System.Text.RegularExpressions.RegexParser.ScanRegex()
 at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
 at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
 at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, String replacement, RegexOptions options)
 at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__31.MoveNext()
```

This PR should just be a simple merge, as the changes are quite minor: the only real difference is that the service prefix (`IImageService.Prefix`) doesn't allow regex patterns anymore...

**Pull request merged**
