### PR TITLE
#369 allow the user override settings in web.config app settings

### PR DESCRIPTION
**Pull request by joebyrne**
using the defined appsetting format the user can override the settings, useful for deployments to Azure etc

e.g. to override the storage hostname the following app setting key would be used

`<add key="ImageProcessor.CloudImageService.Host" value="myimageblobstorage.blob.core.windows.net">`

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
This looks like an interesting way to solve the problem. I wonder if we can (and should) expand upon it to allow overriding other configuration values?

Also, I personally use config transforms during my build process to change settings, is that something you have attempted or considered?

**Comment by octaviobffernandes** [comment]
@JimBobSquarePants I use config transforms in my project to customize these settings per environment/tenant. However, it would be also good to have an enhancement like this to allow the settings to be defined on AppSettings and thus deployed using Azure templating.
Similarly to what was done here for the caching configuration https://github.com/JimBobSquarePants/ImageProcessor/pull/435

**Comment by CasperTDK** [comment]
@JimBobSquarePants config transforms wont work for azure slot swapping - we can only set slot specific settings in appsettings

**Comment by JimBobSquarePants** [comment]
This will need expanded upon and completed then.

**Comment by joebyrne** [comment]
I'll have a look today at what is involved in implementing the other settings.

**Comment by JimBobSquarePants** [comment]
@joebyrne Great, thanks! 👍

**Comment by joebyrne** [comment]
I have pushed changes to allow settings from cache, security or processing config files be managed from web.config / deployment slot app settings. A future update might also be to allow other settings such as whitelists be configured also.

**Comment by JimBobSquarePants** [comment]
Thanks @joebyrne I'll have a good look asap at your changes.

**Comment by JimBobSquarePants** [comment]
@joebyrne Please ignore the bot; I will get round to this eventually!

**Comment by JimBobSquarePants** [comment]
Thanks @joebyrne I'll get a release out asap!

**Comment by merijng** [comment]
@joebyrne @JimBobSquarePants any thoughts about when this feature is getting merged to Master + NuGet? I think this is a feature that many people would like to see.

**Comment by JimBobSquarePants** [comment]
It’s been released for years.

**Pull request merged**
