### PR TITLE
Upgrade to RC1

### PR DESCRIPTION
**Pull request by Jeavon**
Certainly some magic in the change from beta8 to rc1, this was the small amount of info that helped
https://github.com/aspnet/Announcements/issues/98

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Cripes! I know this is cutting edge stuff we're playing with but the amount of changes required is mental, especially with so little information. Thanks for this!

**Comment by Jeavon** [comment]
Yeah, the dotnet5.4 is a magical thing, what, really, what.... it works....

**Comment by JimBobSquarePants** [comment]
Why 5.4? So odd...

**Comment by Jeavon** [comment]
Someone knows, it's in this announcement https://github.com/aspnet/Announcements/issues/98 If you search Twitter for it you get some interesting results

**Pull request merged**
