### PR TITLE
Added enumerable range extension tests

### PR DESCRIPTION
**Pull request by christopherbauer**
Only 1/2 of public methods tested

### CODE REVIEW

**Comment by christopherbauer** [comment]
Had time to finish up.

**Comment by JimBobSquarePants** [comment]
Mergetastic!

**Comment by JimBobSquarePants** [comment]
I'm happy to go with whatever you prefer. Adding smaller feature branches is better practise for git but to be honest this tree must be a shambles. I didn't follow proper practise for years!.

**Comment by christopherbauer** [comment]
You just like that tests are getting written huh :) One of these days I'll 
get to writing tests for some of the complicated stuff!

**Comment by JimBobSquarePants** [comment]
I do... I do indeed :smile:

**Pull request merged**
