### PR TITLE
gojpeg merge

### PR DESCRIPTION
**Pull request by mweber26**
Here is the cleaned up version of the gojpeg conversion (targeting #324)

- I formatted the code as best I can to match the existing project
- The Encoder and Decoder class have all non-essential fields/methods private
- All jpeg helper classes are marked internal to prevent external access

Let me know if you want any more changes to encapsulation or formatting.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
I'm good to merge this as-is. I can apply my particular OCD to the code after (I enjoy that kind of thing) It'll help me to understand properly what is going on when I add documentation anyway. 

Thanks again for this!

**Comment by JimBobSquarePants** [comment]
Hi @mweber26 

As I'm going through the library to port to a generic Image type I've just noticed that there are a couple of fields in the jpeg decoder that are not used.

``` c#
    private byte[] blackPix;
    private int blackStride;
```

https://github.com/JimBobSquarePants/ImageProcessor/blob/Core/src/ImageProcessorCore/Formats/Jpg/JpegDecoderCore.cs#L322

Have you any idea what they are for? I can't figure it out from the golang source.

https://github.com/golang/go/blob/0104a31b8fbcbe52728a08867b26415d282c35d2/src/image/jpeg/reader.go#L126

I'm going to be doing a full cleanup of the class to match the styles of the other formats so I'd like to make sure everything is ok first.

**Comment by mweber26** [comment]
I am pretty sure that they are used for an adobe extension to support CMKY/YPrPbK inside 3 component JPEG.

**Comment by JimBobSquarePants** [comment]
Thanks for that! :+1: 

I reckon I can do without it for now then and go ahead with a cleanup. 

I'm going to be attempting to port it across to match the other encoders in my new generic image branch here. They were easy but this is a different beast. 

https://github.com/JimBobSquarePants/ImageProcessor/tree/2540005d263d7cd223413b314faafe322eee30a5/src/ImageProcessorCore/Formats

I may need to call on you if that's ok?

**Comment by mweber26** [comment]
Sure, I haven't looked at the new encoder framework, but let me know if you run into any problems.

**Comment by JimBobSquarePants** [comment]
Thanks. Appreciate it!

**Pull request merged**
