### PR TITLE
Added optipng to the PNG post processor.

### PR DESCRIPTION
**Pull request by gerbenvd**
Aded optipng to the PNG post processor. This seems to have better results when optimizing with Google PageSpeed Insights

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/JimBobSquarePants/ImageProcessor/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practise as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
I've added optiPNG to the list of post processors that is used when compressing PNG files.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Hi @gerbenvd 

Thanks for taking the time to contribute to the project with your PR. 

Unfortunately there is a long standing issue with optipng that causes Windows Defender to return a false positive.
 
https://github.com/madskristensen/WebEssentials2013/issues/541

I was actually using the program before I received the following issues.

https://github.com/JimBobSquarePants/ImageProcessor/issues/162

https://github.com/JimBobSquarePants/ImageProcessor/issues/255

If we can establish that this is no longer the case then I could accept the PR. Until then I sadly cannot.

Cheers

James

**Comment by gerbenvd** [comment]
Hi Jim!

I understand your considerations. In hindsight, I could have looked better on the open issues, my bad!

Did you consider adding another PNG optimizer? Below you find some references that do a comparision of the various progams out there:

http://www.olegkikin.com/png_optimizers/
https://css-ig.net/png-test-corpus

Would it be an option to make the compression pipe-line configurable, so that you can set which compression programs will be used by means of a configuration file?

**Comment by JimBobSquarePants** [comment]
@gerbenvd I certainly would consider it yes. 

We should probably copy the approach used by [ImageOptimizer](https://github.com/madskristensen/ImageOptimizer/tree/master/src) and improve our compression throughout, except don't use Google guetzli anywhere since the memory requirements are too high for a webserver.

Is that something you could dedicate time to do?

Cheers

James

**Comment by JimBobSquarePants** [comment]
Found the time to do it myself so I've actually just replaced pngout with truepng. This makes any PageSpeed issues go away. 

https://github.com/JimBobSquarePants/ImageProcessor/commit/871fa4a06b8784e85ca4f75cac8566387dd41dfb

**Comment by gerbenvd** [comment]
You fixed it before I got time to respond :) Thanks!!

**Comment by JimBobSquarePants** [comment]
No worries 😄

**Pull request closed without merging**
