### PR TITLE
Add support for .NET 4.5.2

### PR DESCRIPTION
**Pull request by zabulus**

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
@Jeavon Can you do me a favour and cast your eye over this please. You know waaaay more about the new compile/build process than me.

**Comment by Jeavon** [comment]
@zabulus I would like to understand that if you are targeting .Net Framework v4.5.2 why would you choose to use ImageProcessor.Core rather than mature ImageProcessor Framework?

**Comment by zabulus** [comment]
From https://github.com/JimBobSquarePants/ImageProcessor/issues/363
> Not exactly. We are using System.Drawing for saving PNG files in memory and profiler shows that it takes big amount of time. I'm looking 3-rd party libraries for performant PNG encoder or at least with tweaks of compression to decrease it.

**Comment by Jeavon** [comment]
@zabulus did you get this to actually work with framework 4.5.2? I have experimented and while your change to project.json allows a NuGet package to compiled with 4.5.2 binaries in practice I'm unable to use it as System.Numerics.Vectors does not install in a 4.5.2 project, after a quick look at it I think it requires a minimum of 4.6...

**Comment by Jeavon** [comment]
@zabulus I see you mentioned an "additional tweak" in #363 what was that?

**Comment by zabulus** [comment]
I've manually added ```System.Runtime`` as reference. VS marked it as warning but swallowed.
As for ```System.Numerics.Vectors```. I've used nuget package v. 4.0.0 that built for 4.5.2.

**Comment by JimBobSquarePants** [comment]
According to this article it should run on Net4.5.2 when Vectors are installed via Nuget. 

We probably just need to tweak the config appropriately to get System.Runtime correct. 

https://mariantines.com/2015/08/24/simd-support-in-net-framework/

**Comment by JimBobSquarePants** [comment]
Just did some local testing and this all seems to work. Tanks @zabulus for the PR and thanks @Jeavon for testing.

**Comment by JimBobSquarePants** [comment]
This isn't working. I cannot get the nuget package to install into a NET 4.5.2 applicatoin

**Comment by KLuuKer** [comment]
I also tested it last night seems you need to manually install `System.Numerics.Vectors` version 4.0.0
and after that it SHOULD install the ImageProcessorCore package

**Pull request merged**
